import stylesUrl from "~/styles/forms.css";
import twofaqrStylesUrl from "~/styles/2faqr.css";
import { get2faSecret } from "../utils/auth.server";
import { getToken } from "~/cookies";
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import QRCode from "react-qr-code";

export const meta = () => {
    return [{ title: "Register" }];
}

export const links = () => [
    { rel: "stylesheet", href: stylesUrl },
    { rel: "stylesheet", href: twofaqrStylesUrl },
]

export const loader = async ({request}) => {
    // get 2fa secret from server
    const response = await get2faSecret(await getToken(request));
    if (!response || !response.secret) {
        console.log("Failed to get 2fa secret from server" + response);
        return json({ message: "Failed to get 2fa secret from server" }, { status: 500 });
    }
    return json({ secret: response.secret });
}

export default function AddOtp2faMethod() {
    const { secret } = useLoaderData();

    return (
        <main>
            <h1>Add OTP 2FA</h1>
            <p>Scan the QR code below with your authenticator app. Then input a 6-digit code generated by the app into the box below and press Verify.</p>
            <QRCode value={secret} />
            <small><a href={secret}>{secret}</a></small>
            <form>
                <label for="otp">Code</label>
                <input type="number" id="otp" name="otp" />
                <button type="submit">Verify</button>
            </form>
        </main>
    );
}